### ISSUE TITLE
Browsing to spoofax.dev does not redirect to www.spoofax.dev

### ISSUE THREAD

**Issue by maxdekrieger** [metaborg/metaborg.github.io#6]
`https://spoofax.dev` does not redirect to `https://www.spoofax.dev`.

Found this while browsing to the documentation for the first time on a new device.

![afbeelding](https://user-images.githubusercontent.com/25172452/150958037-5cc8f16f-9594-4756-92c5-1e3c2cd15c55.png)

Browser: Firefox 96.0.2 (64-bits), same in Chrome
OS: Windows 10.0.19043

**Comment by Virtlink** [comment]
`spoofax.dev` is now the default, `www.spoofax.dev` redirects there.
